### PR TITLE
Update requirements.txt and README.rst

### PR DESCRIPTION
**Pull request by chanita**
* Add robotframework-seleniumlibrary as a dependency in requirement.txt. 
* Update README.rst to use pip install -r requirement.txt

### CODE REVIEW

**Comment by aaltat** [comment]
Thank you for the enhancement. All looks good and PR is merged.

**Comment by pekkaklarck** [comment]
Are you sure this is a good idea?

- Normal users don't need Invoke or other stuff in requirements.txt.
- `pip install robotframework-seleniumlibrary` isn't any more complicated than `pip install -r requirements.txt`. In fact I consider the former simpler and easier to explain.

**Comment by aaltat** [comment]
For me requirements.txt feels better, although I agree that the project is not meant for users like me. Instead project is meant for users that are new in Python or/and Robot Framework. For those users the txt file can feel even stranger.

When you did say it out loud, I am starting to second guess me. Also I can not decide what would be better. Opinions?

**Comment by pekkaklarck** [comment]
If requirements.txt is used, these additional changes are needed:

- Split dev requirements to separate requirements-dev.txt
- Explain that you need to be in the same directory that requirements.txt (or use relative path)
- Remove references to SL installation instructions because they aren't relevant.

In my opinion the above isn't worth the effort and I'm afraid instructions would end up being more complicated than they used to be.

What I'd do instead:
- In README just have `pip install robotframework-seleniumlibrary` with a note that it install also RF.
- Link RF and SL installation instructions as a reference.
- Have dev requirements in `requirements-dev.txt`. Should be mentioned in BUILD.
- Possibly have normal requirements in `requirements.txt`. Shouldn't be mention it in README to avoid confusion.

**Comment by pekkaklarck** [comment]
@aaltat What do you think about my comment above? The current requirements.txt with dev requirements is not a good idea at all. If you have nothing against it, I'll change installation instructions to contain just `pip install robotframework-seleniumlibrary` and do other changes I propose above.

**Comment by aaltat** [comment]
Sorry, I did forget that I did promise to fix this.

But I think you are right and `requirements.txt` is not good idea and we should do the instead part you did propose.

**Pull request merged**
